name: PyInstaller
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install --upgrade cx_Freeze

      - name: Build with PyInstaller for macos/ubuntu
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller \
            --onefile jellyfinstar.py \
      - name: Build with PyInstaller for windows
        if: matrix.os == 'windows-latest'
        run: |
          cxfreeze jellyfinstar.py
      - name: Copy gflist.txt
        run: |
          cp gflist.txt dist/
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: JellyfinMergeActor-${{ runner.os }}-amd64
          path: dist
